<head>
  <link rel="stylesheet" href="../assets/stylesheets/style.css">
</head>
<body>
  <h2 class="common-Uppercase">
    About
  </h2>
  <p class="common-BodyText">
    <span class="alpha">T</span>he Infra-View GB/IS Generator Bus Temperature Monitor is an encapsulated infrared sensor designed with components that are able to withstand the considerable EMF generated by the iso-phase bus bar.
  </p>
  <p class="common-BodyText">
    Due to thehigh voltages and amperages, in excess of 24 kV/kA, the Infra-View GB/IS is mounted on the bus duct in a direct field of view to the iso-phase bus, in order to remotely measure temperatures from 0°F (-18°C) to 1,000° F (538° C)
  </p>
  <ul id="about-bullets" class="common-BodyText">
    <li>Specifically designed for uprated generators designed to produce greater MW output</li>
    <li>Differing iso-phase bus temperatures indicate unbalanced loads between phases</li>
    <li>Measure iso-phase bus temperature remotely and annunciate alarms conditions</li>
    <li>Eliminate bus failure from heat build-up generated from loose arcing connections</li>
    <li>Used for uprated generators where copper bus work has not been upgraded to match</li>
    <li>Measure flexible link and transformer connections</li>
    <li>Bus Temperatures are measured to within +/- 1.0°F or C with a span from 0°F (-18°C) to 1,000° F (538°C)</li>
    <li>Temperature data is transmitted via a loop powered 24 VDC/4-20 mA connection directly to the control room DCS</li>
    <li>Acquired data of each iso-phase can then be recorded into a history file for comparison to MW load and iso-phase bus temperature</li>
    <li>Overall load shedding or inspections can then be performed based on this valuable data preserving the integrity on the iso-phase bus work</li>
  </ul>
</body>
