<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title>Generator Bus Bar Thermometer | About</title>

  <meta name="description" content="Infra-View® Infrared Boiler Thermometer is a patented, remote sensing infrared detector, supplied with a rugged protective-cooling jacket that can be permanently flange mounted on any port, door or penetration into the boiler or furnace.">

  <meta name="keywords" content="boiler, power, generator, nuclear, Little Ferry, pipe plug, energy, JNT, industry, performance, manufacturer, technical, plug, tube plug, exit gas, furnace, high pressure, feed water, acoustic, leak, detector, sound, RADS">

  <link rel="stylesheet" href="./assets/css/style.css">

  <meta property="og:title" content="JNT Technical Services">
  <meta property="og:url" content="http://www.infra-view.com/">
  <meta property="og:description" content="Infra-View® Infrared Boiler Thermometer is a patented, remote sensing infrared detector, supplied with a rugged protective-cooling jacket that can be permanently flange mounted on any port, door or penetration into the boiler or furnace.">

  <link rel="apple-touch-icon" sizes="57x57" href="/favicons/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/favicons/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/favicons/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/favicons/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/favicons/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/favicons/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/favicons/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/favicons/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/favicons/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicons/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
  <link rel="manifest" href="/favicons/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/favicons/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
</head>
  <?php include "./nav/header-nav.html" ?>
<body>
    <div class="link-row">
      <div class="cols container-lg">
        <div class="left" id="content">
          <h2 class="common-Uppercase">
            About
          </h2>
          <p class="common-BodyText">
            <span class="alpha">T</span>he Infra-View GB/IS Generator Bus Temperature Monitor is an encapsulated infrared sensor designed with components that are able to withstand the considerable EMF generated by the iso-phase bus bar.
          </p>
          <p class="common-BodyText">
            Due to thehigh voltages and amperages, in excess of 24 kV/kA, the Infra-View GB/IS is mounted on the bus duct in a direct field of view to the iso-phase bus, in order to remotely measure temperatures from 0°F (-18°C) to 1,000° F (538° C)
          </p>
          <ul id="about-bullets" class="common-BodyText">
            <li>Specifically designed for uprated generators designed to produce greater MW output</li>
            <li>Differing iso-phase bus temperatures indicate unbalanced loads between phases</li>
            <li>Measure iso-phase bus temperature remotely and annunciate alarms conditions</li>
            <li>Eliminate bus failure from heat build-up generated from loose arcing connections</li>
            <li>Used for uprated generators where copper bus work has not been upgraded to match</li>
            <li>Measure flexible link and transformer connections</li>
            <li>Bus Temperatures are measured to within +/- 1.0°F or C with a span from 0°F (-18°C) to 1,000° F (538°C)</li>
            <li>Temperature data is transmitted via a loop powered 24 VDC/4-20 mA connection directly to the control room DCS</li>
            <li>Acquired data of each iso-phase can then be recorded into a history file for comparison to MW load and iso-phase bus temperature</li>
            <li>Overall load shedding or inspections can then be performed based on this valuable data preserving the integrity on the iso-phase bus work</li>
          </ul>
        </div>
        <div class="right" id="images">
          <h2 class="common-Uppercase center">
            Infra-View&reg; Boiler Thermometer
          </h2>
          <?php include "./images/_default.html" ?>
        </div>
      </div>
    </div>
</body>
<?php include "../partials/footer.html" ?>
